APP_HOST: 'cheeseformice.localhost'
APP_PORT: '3000'

# Kamal deployment
RAILS_MASTER_KEY: 'change_me'
DOCKER_REGISTRY_PASSWORD: 'change_me'
POSTGRES_PASSWORD: 'change_me'

test:
  # SELENIUM_DRIVER: 'selenium_chrome'
  SELENIUM_DRIVER: 'selenium_chrome_headless'
