default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: cheeseformice_development

test:
  <<: *default
  database: cheeseformice_test

production:
  <<: *default
  database: cheeseformice_production
  username: cheeseformice
  password: <%= ENV["CHEESEFORMICE_DATABASE_PASSWORD"] %>
